platform :ios, '10.0’
target ‘SFWork' do
pod 'AFNetworking', '~>3.1.0'
pod 'ReactiveObjC', '~> 3.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'TZImagePickerController'
pod 'MJRefresh', '~> 3.1'
pod 'Reachability', '~> 3.2'
pod 'IQKeyboardManager', '~> 5.0.3'
pod 'YYKit', '~> 1.0.9'
pod 'Masonry'
pod 'SDAutoLayout', '~> 2.1.3'
pod 'AliyunOSSiOS'
pod 'JPush'
pod 'RongCloudIM/IMLib', '~> 2.8.3'
pod 'RongCloudIM/IMKit', '~> 2.8.3'

pod 'AMapSearch'
pod 'AMapLocation'
pod 'AMap3DMap'

#pod 'SDWebImage', '~> 4.0.0'

end
